CREATE OR REPLACE FUNCTION UPDATE_CAR(
     P_ID CARS.CAR_ID%TYPE,  
    P_MODEL CARS.MODEL%TYPE,
    P_DATE_OF_MANUF CARS.DATE_OF_MANUFACTURE%TYPE  
)

RETURN NUMBER
AS
 V_YEAR NUMBER;
 
 BEGIN
   UPDATE CARS 
   SET 
   MODEL = P_MODEL,
   DATE_OF_MANUFACTURE =  P_DATE_OF_MANUF
   WHERE CAR_ID = P_ID;
   
   SELECT EXTRACT(YEAR FROM DATE_OF_MANUFACTURE)
   INTO V_YEAR
   FROM CARS 
   WHERE CAR_ID = P_ID;   
 
 RETURN V_YEAR;
 END UPDATE_CAR;
 /